### ISSUE TITLE
Does not work on Cinnamon 3.4.4 LM 18.2

### ISSUE THREAD

**Issue by Marcosdw** [germanfr/cinnamon-transparent-panels#11] opened 2017-07-12 07:00 UTC
Hello, 

Does not work on Cinnamon 3.4.4 LM 18.2

Thank's fix

____
Sorry I use an online translator French English

**Comment by germanfr** [comment] 2017-07-12 07:52
Hi, can you give me some details? It's working fine here.

**Comment by germanfr** [comment] 2017-07-15 18:48
I'm closing this since it seems to be a duplicate of #10

**Closed by germanfr** 2017-07-15 18:48 UTC

**Comment by Marcosdw** [comment] 2017-07-16 03:35
Delete all files Transparent panels
reinstall 
work fine
